version = 1
[custom]
enable_rule_generator = false
overwrite_original_rules = false

clash_rule_base = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/config/all_base.tpl"

add_emoji = false
remove_old_emoji = true

exclude_remarks = [(å®˜ç½‘|äº§å“|å¹³å°|å›å›½|æ›´æ–°)]

[[custom_groups]]
import = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/config/groups.toml

[[custom_groups]]
name = "ğŸ€ Proxy"
type = "select"
rule = ["â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line", "[]ğŸ€ Direct"]