version = 1
[custom]
enable_rule_generator = false
overwrite_original_rules = false

clash_rule_base = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/config/all_base.tpl"
surge_rule_base = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/config/all_base.tpl"

add_emoji = true
remove_old_emoji = true
[[emoji]]
match = "HK"
emoji = "ğŸŸ"

[[emoji]]
match = "SG"
emoji = "â£ï¸"

[[emoji]]
match = "JP"
emoji = "ğŸ¥§"

[[emoji]]
match = "KR"
emoji = "ğŸ¬"

[[emoji]]
match = "TW"
emoji = "ğŸ¦"

[[emoji]]
match = "AU"
emoji = "ğŸ°"

[[emoji]]
match = "DE"
emoji = "ğŸŒ·"

[[emoji]]
match = "UK"
emoji = "ğŸ¦Š"

[[emoji]]
match = "US"
emoji = "ğŸ§"

[[emoji]]
match = "RU"
emoji = "â˜”"

[[emoji]]
match = "IN"
emoji = "ğŸµ"

[[emoji]]
match = "MY"
emoji = "ğŸˆ"

[[emoji]]
match = "TU"
emoji = "ğŸ•Šï¸"

[[emoji]]
match = "AR"
emoji = "ğŸ—ï¸"

[[emoji]]
match = "TH"
emoji = "ğŸƒ"

[[emoji]]
match = "BO"
emoji = "ğŸ§¸"

[[emoji]]
match = "ES"
emoji = "ğŸ¼"

[[emoji]]
match = "NL"
emoji = "ğŸ­"

[[emoji]]
match = "PH"
emoji = "ğŸš‡"

[[emoji]]
match = "CA"
emoji = "ğŸ’«"

[[emoji]]
match = "PL"
emoji = "â™¦ï¸"

[[emoji]]
match = "ID"
emoji = "ğŸ—ï¸"

[[emoji]]
match = "VN"
emoji = "ğŸ¥‚"

[[emoji]]
match = "CH"
emoji = "ğŸ¤"

[[emoji]]
match = "MX"
emoji = "ğŸ“•"

[[emoji]]
match = "IT"
emoji = "ğŸŒº"

[[emoji]]
match = "FR"
emoji = "ğŸ„"

[[emoji]]
match = "HU"
emoji = "ğŸŒ¨ï¸"

[[emoji]]
match = "SE"
emoji = "ğŸ’"

[[emoji]]
match = "LU"
emoji = "ğŸ¸"

[[emoji]]
match = "UA"
emoji = "ğŸ°"

[[emoji]]
match = "AT"
emoji = "ğŸ§"

[[emoji]]
match = "EX"
emoji = "ğŸ©"

[[emoji]]
match = "D:"
emoji = "â„ï¸"

[[emoji]]
match = "T:"
emoji = "ğŸ­"

exclude_remarks = [(å®˜ç½‘|äº§å“|å¹³å°|å›å›½|æ›´æ–°)]

[[custom_groups]]
name = "ğŸ€ Proxy"
type = "select"
rule = ["â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line", "[]ğŸ€ Direct"]

[[custom_groups]]
name = "ğŸº Pixiv"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ Twitter"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ’¤ Manga"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸƒ TW|SC", "[]ğŸ€ Direct", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸŒ± Ecchi"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸƒ TW|SC", "[]ğŸ€ Direct", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸˆ Telegram"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "â˜• Globalmedia"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ’§ Domestic"
type = "select"
rule = ["[]ğŸ€ Direct", "[]ğŸ€ Proxy", "[]ğŸ¼ Reject", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ”” Other"
type = "select"
rule = ["[]ğŸ€ Proxy", "[]ğŸ€ Direct", "[]ğŸ¼ Reject", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ’œ RELAY"
type = "select"
rule = ["ğŸ¥ RELAY|TS", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸƒ TW|SC", "EX", "RE.A", "RE.B", "RE.C", "RE.D", "RE.E", "RE.F", "RE.G", "RE.H", "RE.I", "RE.J", "RE.K", "RE.L", "RE.M", "RE.N", "RE.O", "RE.P", "RE.Q", "RE.R", "RE.S", "RE.T", "RE.U", "RE.V", "RE.W", "RE.X", "RE.Y", "RE.Z"]

[[custom_groups]]
name = "ğŸ® Line"
type = "select"
rule = ["[]ğŸ€ Direct", "[]ğŸ¼ Reject", "Data:", "Time:", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "EX", "PC.A", "PC.B", "PC.C", "PC.D", "PC.E", "PC.F", "PC.G", "PC.H", "PC.I", "PC.J", "PC.K", "PC.L", "PC.M", "PC.N", "PC.O", "PC.P", "PC.Q", "PC.R", "PC.S", "PC.T", "PC.U", "PC.V", "PC.W", "PC.X", "PC.Y", "PC.Z", "RE.A", "RE.B", "RE.C", "RE.D", "RE.E", "RE.F", "RE.G", "RE.H", "RE.I", "RE.J", "RE.K", "RE.L", "RE.M", "RE.N", "RE.O", "RE.P", "RE.Q", "RE.R", "RE.S", "RE.T", "RE.U", "RE.V", "RE.W", "RE.X", "RE.Y", "RE.Z", ".*"]

[[custom_groups]]
name = "ğŸŒ¸ JP|SC"
type = "select"
rule = ["[]ğŸ¥ RELAY|JP|TS", "(.*JP)"]

[[custom_groups]]
name = "ğŸŒ¹ HK|SC"
type = "select"
rule = ["[]ğŸ¯ RELAY|HK|TS", "(.*HK)"]

[[custom_groups]]
name = "ğŸŒ™ SG|SC"
type = "select"
rule = ["[]ğŸ± RELAY|SG|TS", "(.*SG)"]

[[custom_groups]]
name = "ğŸ† US|SC"
type = "select"
rule = ["[]ğŸ•Šï¸ RELAY|US|TS", "(.*US)"]

[[custom_groups]]
name = "ğŸƒ TW|SC"
type = "select"
rule = ["[]ğŸ¨ RELAY|TW|TS", "(.*TW)"]

[[custom_groups]]
name = "ğŸ¥ RELAY|JP|TS"
type = "url-test"
rule = ["RE(.*JP.)(.*1x)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
timeout = 5
tolerance = 100
lazy = true

[[custom_groups]]
name = "ğŸ¯ RELAY|HK|TS"
type = "url-test"
rule = ["RE(.*HK.)(.*1x)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
timeout = 5
tolerance = 100
lazy = true

[[custom_groups]]
name = "ğŸ± RELAY|SG|TS"
type = "url-test"
rule = ["RE(.*SG.)(.*1x)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
timeout = 5
tolerance = 100
lazy = true

[[custom_groups]]
name = "ğŸ•Šï¸ RELAY|US|TS"
type = "url-test"
rule = ["RE(.*US.)(.*1x)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
timeout = 5
tolerance = 100
lazy = true

[[custom_groups]]
name = "ğŸ¨ RELAY|TW|TS"
type = "url-test"
rule = ["RE(.*TW.)(.*1x)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
timeout = 5
tolerance = 100
lazy = true

[[custom_groups]]
name = "ğŸ€ Direct"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸ¼ Reject"
type = "select"
rule = ["[]REJECT"]

[[rulesets]]
ruleset = "ğŸ€ Direct"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Direct.list"

[[rulesets]]
group = "ğŸ€ Direct"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Localareanetwork.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Fuckfalun.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Fuckmangaad.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Fuckscam.list"

[[rulesets]]
group = "ğŸº Pixiv"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Pixiv.list"

[[rulesets]]
group = "ğŸ Twitter"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Twitter.list"

[[rulesets]]
group = "ğŸ’¤ Manga"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Manga.list"

[[rulesets]]
group = "ğŸŒ± Ecchi"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Ecchi.list"

[[rulesets]]
group = "ğŸˆ Telegram"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "â˜• Globalmedia"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Speedtest.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/raw/main/rule/Fucktaptap.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Extra/ChinaIP.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ”” Other"
ruleset = "[]MATCH"