[[emoji]]
match = "HK"
emoji = "ğŸŸ"

[[emoji]]
match = "SG"
emoji = "â£ï¸"

[[emoji]]
match = "JP"
emoji = "ğŸ¥§"

[[emoji]]
match = "KR"
emoji = "ğŸ¬"

[[emoji]]
match = "TW"
emoji = "ğŸ¦"

[[emoji]]
match = "AU"
emoji = "ğŸ°"

[[emoji]]
match = "DE"
emoji = "ğŸŒ·"

[[emoji]]
match = "UK"
emoji = "ğŸ¦Š"

[[emoji]]
match = "US"
emoji = "ğŸ§"

[[emoji]]
match = "RU"
emoji = "â˜”"

[[emoji]]
match = "IN"
emoji = "ğŸµ"

[[emoji]]
match = "MY"
emoji = "ğŸˆ"

[[emoji]]
match = "TU"
emoji = "ğŸ•Šï¸"

[[emoji]]
match = "AR"
emoji = "ğŸ—ï¸"

[[emoji]]
match = "TH"
emoji = "ğŸƒ"

[[emoji]]
match = "BO"
emoji = "ğŸ§¸"

[[emoji]]
match = "ES"
emoji = "ğŸ¼"

[[emoji]]
match = "NL"
emoji = "ğŸ­"

[[emoji]]
match = "PH"
emoji = "ğŸš‡"

[[emoji]]
match = "CA"
emoji = "ğŸ’«"

[[emoji]]
match = "PL"
emoji = "â™¦ï¸"

[[emoji]]
match = "ID"
emoji = "ğŸ—ï¸"

[[emoji]]
match = "VN"
emoji = "ğŸ¥‚"

[[emoji]]
match = "CH"
emoji = "ğŸ¤"

[[emoji]]
match = "MX"
emoji = "ğŸ“•"

[[emoji]]
match = "IT"
emoji = "ğŸŒº"

[[emoji]]
match = "FR"
emoji = "ğŸ„"

[[emoji]]
match = "HU"
emoji = "ğŸŒ¨ï¸"

[[emoji]]
match = "SE"
emoji = "ğŸ’"

[[emoji]]
match = "LU"
emoji = "ğŸ¸"

[[emoji]]
match = "UA"
emoji = "ğŸ°"

[[emoji]]
match = "AT"
emoji = "ğŸ§"

[[emoji]]
match = "EX"
emoji = "ğŸ©"

[[emoji]]
match = "Data:"
emoji = "â„ï¸"

[[emoji]]
match = "Time:"
emoji = "ğŸ­"