[[custom_groups]]
name = "ğŸ€ Proxy"
type = "select"
rule = ["â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line", "[]ğŸ€ Direct"]

[[custom_groups]]
name = "ğŸº Pixiv"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ Twitter"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ’¤ Manga"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸƒ TW|SC", "[]ğŸ€ Direct", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸŒ± Ecchi"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸƒ TW|SC", "[]ğŸ€ Direct", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸˆ Telegram"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "â˜• Streaming"
type = "select"
rule = ["[]ğŸ€ Proxy", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ’§ Domestic"
type = "select"
rule = ["[]ğŸ€ Direct", "[]ğŸ€ Proxy", "[]ğŸ¼ Reject", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸµ Block"
type = "select"
rule = ["[]ğŸ¼ Reject", "[]ğŸ€ Direct"]

[[custom_groups]]
name = "ğŸ”” Other"
type = "select"
rule = ["[]ğŸ€ Proxy", "[]ğŸ€ Direct", "[]ğŸ¼ Reject", "[]ğŸ® Line"]

[[custom_groups]]
name = "ğŸ’œ RELAY"
type = "select"
rule = ["[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "[]ğŸƒ TW|SC", "EX", "RE.JP", "RE.HK", "RE.SG", "RE.US", "RE.TW", "RE.A", "RE.B", "RE.C", "RE.D", "RE.E", "RE.F", "RE.G", "RE.H", "RE.I", "RE.J", "RE.K", "RE.L", "RE.M", "RE.N", "RE.O", "RE.P", "RE.Q", "RE.R", "RE.S", "RE.T", "RE.U", "RE.V", "RE.W", "RE.X", "RE.Y", "RE.Z"]

[[custom_groups]]
name = "ğŸ® Line"
type = "select"
rule = ["[]ğŸ€ Direct", "[]ğŸ¼ Reject", "Data:", "Time:", "â„ï¸ IPLC", "[]ğŸ’œ RELAY", "[]ğŸŒ¸ JP|SC", "[]ğŸŒ¹ HK|SC", "[]ğŸŒ™ SG|SC", "[]ğŸ† US|SC", "EX", "PC.A", "PC.B", "PC.C", "PC.D", "PC.E", "PC.F", "PC.G", "PC.H", "PC.I", "PC.J", "PC.K", "PC.L", "PC.M", "PC.N", "PC.O", "PC.P", "PC.Q", "PC.R", "PC.S", "PC.T", "PC.U", "PC.V", "PC.W", "PC.X", "PC.Y", "PC.Z", "RE.A", "RE.B", "RE.C", "RE.D", "RE.E", "RE.F", "RE.G", "RE.H", "RE.I", "RE.J", "RE.K", "RE.L", "RE.M", "RE.N", "RE.O", "RE.P", "RE.Q", "RE.R", "RE.S", "RE.T", "RE.U", "RE.V", "RE.W", "RE.X", "RE.Y", "RE.Z", ".*"]

[[custom_groups]]
name = "ğŸŒ¸ JP|SC"
type = "select"
rule = ["ğŸ¥ RELAY|JP|TS", "(.*JP)"]

[[custom_groups]]
name = "ğŸŒ¹ HK|SC"
type = "select"
rule = ["ğŸ¯ RELAY|HK|TS", "(.*HK)"]

[[custom_groups]]
name = "ğŸŒ™ SG|SC"
type = "select"
rule = ["ğŸ± RELAY|SG|TS", "(.*SG)"]

[[custom_groups]]
name = "ğŸ† US|SC"
type = "select"
rule = ["ğŸ•Šï¸ RELAY|US|TS", "(.*US)"]

[[custom_groups]]
name = "ğŸƒ TW|SC"
type = "select"
rule = ["ğŸ¨ RELAY|TW|TS", "(.*TW)"]

[[custom_groups]]
name = "ğŸ€ Direct"
type = "select"
rule = ["[]DIRECT"]

[[custom_groups]]
name = "ğŸ¼ Reject"
type = "select"
rule = ["[]REJECT"]