
[[rulesets]]
group = "ğŸ€ Direct"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Direct.list"

[[rulesets]]
group = "ğŸ€ Direct"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Localareanetwork.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Scam.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Mangaad.list"

[[rulesets]]
group = "ğŸº Pixiv"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Pixiv.list"

[[rulesets]]
group = "ğŸ Twitter"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Twitter.list"

[[rulesets]]
group = "ğŸ’¤ Manga"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Manga.list"

[[rulesets]]
group = "ğŸŒ± Ecchi"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Ecchi.list"

[[rulesets]]
group = "ğŸˆ Telegram"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "â˜• Streaming"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/ruleset/surge/Speedtest.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyLite.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ”” Other"
ruleset = "[]MATCH"