[[rulesets]]
ruleset = "ğŸ€ Direct"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Direct.list"

[[rulesets]]
group = "ğŸ€ Direct"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Localareanetwork.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Fuckfalun.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Fuckmangaad.list"

[[rulesets]]
group = "ğŸ¼ Reject"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Fuckscam.list"

[[rulesets]]
group = "ğŸº Pixiv"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Pixiv.list"

[[rulesets]]
group = "ğŸ Twitter"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Twitter.list"

[[rulesets]]
group = "ğŸ’¤ Manga"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Manga.list"

[[rulesets]]
group = "ğŸŒ± Ecchi"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Ecchi.list"

[[rulesets]]
group = "ğŸˆ Telegram"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "â˜• Globalmedia"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Speedtest.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ€ Proxy"
ruleset = "https://gitlab.com/ShiroSakurairo/subrule/-/raw/main/rule/Fucktaptap.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Surge/Ruleset/Extra/ChinaIP.list"

[[rulesets]]
group = "ğŸ’§ Domestic"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸ”” Other"
ruleset = "[]MATCH"